// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolRoleManagement.Data;

namespace SchoolRoleManagement.Migrations
{
    [DbContext(typeof(RoleDbContext))]
    [Migration("20200119043215_newupdatekd")]
    partial class newupdatekd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolRoleManagement.Models.RoleTransition", b =>
                {
                    b.Property<int>("RoleTransitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromTeacherRoleId")
                        .HasColumnType("int");

                    b.Property<int>("ToTeacherRoleId")
                        .HasColumnType("int");

                    b.HasKey("RoleTransitionId");

                    b.HasIndex("FromTeacherRoleId");

                    b.HasIndex("ToTeacherRoleId");

                    b.ToTable("Transitions");
                });

            modelBuilder.Entity("SchoolRoleManagement.Models.TeacherRole", b =>
                {
                    b.Property<int>("TeacherRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("RequireTenure")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherRoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SchoolRoleManagement.Models.RoleTransition", b =>
                {
                    b.HasOne("SchoolRoleManagement.Models.TeacherRole", "From")
                        .WithMany()
                        .HasForeignKey("FromTeacherRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SchoolRoleManagement.Models.TeacherRole", "To")
                        .WithMany()
                        .HasForeignKey("ToTeacherRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
